export enum DataSourceEnum {
  PG_DATA_SOURCE = 'PG_DATA_SOURCE',
}




export enum RepositoryEnum {
    PRODUCT_REPOSITORY = 'PG_DATA_SOURCE',
    CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY",
    COCINA_REPOSITORY = "COCINA_REPOSITORY"
}
