export enum RepositoryEnum {
    PRODUCT_REPOSITORY = "PRODUCT_REPOSITORY",
    CATEGORY_REPOSITORY = "CATEGORY_REPOSITORY",
    COCINA_REPOSITORY = "COCINA_REPOSITORY",
    COCINERO_REPOSITORY = "COCINERO_REPOSITORY"
}

